name: run-e2e-tests-on-docker
# source: https://github.com/marketplace/actions/install-poetry-action


on:
  push:
    branches: [ "main" ]

jobs:
  e2e-tests-docker:
    runs-on: ubuntu-22.04
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: run-reusable-actions
        id: run-reusable-actions
        uses: ./.github/actions

      - name: Install python
        uses: actions/setup-python@v5
        with:
         python-version: '3.10.12'
