name: strudel-test
on:
  workflow_dispatch:
jobs:
  run-strudel-test:
    uses: strudelbots/strudel-public/.github/workflows/run_strudel_test.yml@v0.8.0
    secrets:
        strudel_access_key: ${{ secrets.STRUDEL_ACCESS_KEY_ID }}
        strudel_secret_key: ${{ secrets.STRUDEL_SECRET_KEY }}
